### ISSUE TITLE
How screwed am I?

### ISSUE THREAD

**Issue by doktorjw** [thenickdude/PlanC#11]
How screwed am I if I don't have an adb directory? From looking at my wife's machine, crashplan is no longer installed, and there is no adb directory. I don't remember uninstalling it ... I don't want to believe that Code42 actually uninstalled it after the cut-off date (they didn't uninstall mine, but my adb directory is gone, too).

**Comment by mr-flibble** [comment]
Helo, I would recommend reading this topick: https://www.reddit.com/r/Crashplan/comments/9o1l04/do_you_plan_to_use_crashplan_free_after_october/

Code42 did deleted users encryption keys and client config on 22. October. So if you don't have any backup, I don't see any chance other than contacting Code42 :(

**Comment by audiolomb** [comment]
Unfortunately, I believe you are out of luck.
I contacted CrashPlan before I found this project and they basically told me they could not help me in any way to recover the backup.
Maybe they still have the keys (maybe!) but for sure they will not help you in any way. Not sure if this is the best marketing strategy, but that's what they're doing.

**Comment by thenickdude** [comment]
It looks like very old CrashPlan databases contained a cp.properties file that had a "secureDataKey" field in it, and this is the key for decrypting the database without an adb directory. If you happen to have one of those files with that entry in it, please track #17 for updates.
