### ISSUE TITLE
Need a little help getting started

### ISSUE THREAD

**Issue by WiseGuyNL** [thenickdude/PlanC#12]
Hey Guys,

Sorry in advance, total Linux noob here....
I need a little help getting started, the readme assumes basic knowledge of linux which I am lacking.
I installed ubuntu in a VM just for this purpose, downloaded the PlanC files (in ZIP) and put them in /home/PlanC-master
I copied the adb folder with my key into /home/adb
The first step should be decrypting my key but I can't get the plan-c command to work. 
How do I install the PlanC package?

**Comment by ghzgod** [comment]
Hey you need to make plan-c an executable.  The way you do this is type sudo chmod+x "path/to/plan-c" This will let you run plan-c within your linux shell.  Let me know if you get stuck.
