### ISSUE TITLE
Listing files works, but restoring generates an error

### ISSUE THREAD

**Issue by argoneus** [thenickdude/PlanC#13]
I've recovered my key and can list the files contained in my backup archive.  I assume the filenames are encrypted as well, and wouldn't be able to see the names unless the key was valid... correct?  One oddity is whenever I list the archive contents, an error is thrown at at end, before the command exits:

    terminate called after throwing an instance of 'BadPaddingException'
    what():  Bad padding

I'm receiving the following error whenever I try to restore (either a single file or a path):

```Caching block indexes in memory...
Restoring files...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open archive file manifest /path/to/my/archive/cpfmf
```
Any suggestions would be much appreciated!

**Comment by thenickdude** [comment]
Yes, filenames are encrypted, so the key should be correct.

The bad padding exception could be triggered by a corrupted file in the backup.

In theory that "failed to open archive file manifest" error can only be triggered if the `/path/to/my/archive/cpfmf` file couldn't be opened. Make sure it exists and has file permissions that allows it to be read.
