### ISSUE TITLE
Thankyou!

### ISSUE THREAD

**Issue by level323** [thenickdude/PlanC#14]
I just came here to say a big "thankyou" for this software.

My father managed to toast one of his Windows drives and discovered that he had no recent backups of it (due to a procedural error). However, up until Crashplan closed down I had been using it to backup that drive for him.

...and today I used your software to recover the lost files (well, up to Oct 2018). 

On behalf of my father, I thank you!

**Comment by thenickdude** [comment]
Happy to help!
