### ISSUE TITLE
Unsupported path format error

### ISSUE THREAD

**Issue by straxhaber** [thenickdude/PlanC#15]
I'm getting an "Unsupported path format" error when I run PlanC. Can anyone help me figure out what is going on? Thanks so much :)

Command:
```~/aPath/plan-c --key KEY --archive 602703654489162270 --command list```
("KEY" is the 109-character hex version of my custom CrashPlan key)

Output:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: decryptEncryptedPath: Unsupported path format
Abort trap: 6
```

**Comment by thenickdude** [comment]
The key is expected to be 112 characters long (448 bit), can you double check it?

**Comment by thenickdude** [comment]
Assuming that you just miscounted your key characters, support for this older Crashplan version is being developed in #17, so please track that for updates.

**Comment by straxhaber** [comment]
Awesome, thanks! It's really great that you put this together and shared it.

**Comment by thenickdude** [comment]
Can you email me the first few kilobytes of the `cpfmf` file from your archive? This file contains a list of all the filenames in the backup, but those pathnames are encrypted so this shouldn't leak any personal information. n.sherlock@gmail.com

**Comment by thenickdude** [comment]
If you can build my latest commit, it should add support for these old-style paths now, although it might fail somewhere further down the chain instead.

**Comment by thenickdude** [comment]
I've now released version 0.2 which contains support for these old-style paths:

https://github.com/thenickdude/PlanC/releases/tag/v0.2

Another user was able to successfully perform a restore using this one.

**Comment by straxhaber** [comment]
Thanks! I got this error with the newest version:

```
Failed to decrypt path for file at offset 0
libc++abi.dylib: terminating with uncaught exception of type BadPaddingException: Bad padding
```

Could this be caused by a bad key or is it something else?

**Comment by thenickdude** [comment]
That's very likely to be due to the wrong key. If you want me to double check you can email me the first 512 bytes of your cpfmf file from your archive and your key (this will reveal the first 3 or so filenames of your backup to me, probably /, /boot and /home) n.sherlock@gmail.com

**Comment by straxhaber** [comment]
Hi @thenickdude - it's alright, but I appreciate the offer! I was able to find an alternative source for restoring the data a few months ago. I haven't had time to sift through that yet to make sure it has what I need, but I'll let you know if it doesn't and I need to further explore Plan-C. **Regardless, you're a hero for putting this on GitHub and helping people recover vital backups!** I'll go ahead and close this issue for now as it's likely I am using the wrong key.
