### ISSUE TITLE
Recover key from cp.properties

### ISSUE THREAD

**Issue by jacobhl** [thenickdude/PlanC#17]
So back in 2013 I used Crashplan locally on my NAS. If I remember it correctly I synced my laptop to my NAS using crashplan, and then my NAS to Crashplan cloud. The install have longe since been purged from the NAS, but the datafolder still exists.

In the folder I have cp.properties file with secureDataKey (148-character long base64 (removing \ which seem to be used for escape)), userPassword(<28-characters>:<12-characters> base64) and securityKeyType=AccountPassword.

Trying to base64-decode the 148-character SecureDataKey and using as --key argument is giving me a 'Unsupported path format'. Is this in any way or form the correct key I have found, or do I need another key?

**Comment by thenickdude** [comment]
I've never seen a secureDataKey field in cp.properties before, that is curious. If you're lucky it may indeed be the archive encryption key, but it'll be encrypted with a password (probably your account password, maybe an archive password).

Plan-C has code for decrypting secureDataKeys out of the `adb`, but it doesn't look for them in cp.properties. Which operating system are you using now, and can you send me your cp.properties file? (n.sherlock@gmail.com). I can add an option for loading the key from there for you to try out.

**Comment by jacobhl** [comment]
Thanks a bunch - I've mailed it to you. The file is from October 2013 :).

I've compiled it for Linux, but can easily run it from Windows as well.

Are there any filesystem hiccups I should be aware of? Can I have the Crashplan database on a Windows share while extracting from a linux OS for example?

**Comment by thenickdude** [comment]
Please try out the latest commit I've pushed, you should be able to run "./plan-c recover-key --cpproperties ./cp.properties" to decrypt the key from the file you sent me (you then need to enter the encryption password, which I'm guessing is either your account password or an archive password).

Plan C dies when writing to a Windows share because it fails to create directories with colons in the name (e.g. "restored/C:/WINDOWS/Installer.log"), and probably other problems too. There's no technical reason why this couldn't be supported, but I don't use Windows and don't have a development environment to test this on, so I probably won't bother adding support myself.

**Comment by jacobhl** [comment]
It recovered a 112-character key after I remembered the right password (wrong passwords failed)! However, after I run list on the archive with the new key, it gives an error of:
terminate called after throwing an instance of 'std::runtime_error'
  what():  decryptEncryptedPath: Unsupported path format
Aborted (core dumped)

All archives and software moved to full linux OS.

**Comment by thenickdude** [comment]
~~Unfortunately that likely means that the key doesn't decrypt the backup properly.~~ (EDIT: Actually, this is wrong, nothing has been decrypted at the point this message gets thrown). I'll take a look and see if I can add useful diagnostics here to confirm.

**Comment by thenickdude** [comment]
I've pushed a new commit which makes this diagnostic more detailed, please give it a go. If you're lucky this is just a complaint that the path is in an older format that doesn't have support yet.

**Comment by jacobhl** [comment]
Pretty good guess, I'll say :):
terminate called after throwing an instance of 'std::runtime_error'
  what():  decryptEncryptedPath: Unsupported path format, magic = -347958548, version = 147, encryption = 26

**Comment by thenickdude** [comment]
Those values don't make sense in the format I know for the file manifest, so it's probably a format I haven't seen. Can you email me the first few kilobytes of your `cpfmf` file from the backup archive? This is the file manifest which lists all the files in the backup.

**Comment by thenickdude** [comment]
Oh yep it looks like the older version of Crashplan just used no header at all to indicate which encryption was being used for pathnames, it just always uses Blowfish-128, I decrypted your first two filepaths by hand using your key as "/" and "/Users". Looks hopeful for full recovery.

**Comment by jacobhl** [comment]
Sounds absolutely awesome. I have enormous respect for the work you are
putting into this project :)

**Comment by jacobhl** [comment]
Latest commit worked perfectly on my database. Thank you very much for all the work you put into this.
