### ISSUE TITLE
Simpler way to browse revisions

### ISSUE THREAD

**Issue by umaar** [thenickdude/PlanC#18]
Hey this is a great tool! Well written documentation also, thanks!

Not sure how it all works but would it be possible to "mount" the various revisions as different folders or something? So we can browse what sort of files are present using Finder? Maybe not the right solution. Just finding it hard to understand files from the command line with the `list-all` flag, as there's so much there!

Or alternatively, the prefix flag is helpful but maybe having a way to exclude folders from being listed and/or restored would be good?

**Comment by thenickdude** [comment]
These are fair suggestions, but I have no plans to add these features, sorry. I suggest restoring everything and picking through it later.
