### ISSUE TITLE
Is there adb folder on CrashPlan 4.4.1?

### ISSUE THREAD

**Issue by mr-flibble** [thenickdude/PlanC#2]
Hello, first thanks for this project!
I wanted to create backup of adb folder on old CrashPlan home 4.4.1 on Windows Server 2003 (don't ask :) ) 
But adb folder is not in conf folder. I run search for *adb* but adb folder is not on system drive.

Does that mean I'm out of luck? Thanks 

![image](https://user-images.githubusercontent.com/5197625/46919048-8326a180-cfd9-11e8-8817-6c4f2e7fc03b.png)

![image](https://user-images.githubusercontent.com/5197625/46918796-d77c5200-cfd6-11e8-8d2f-c063081e7a9d.png)

**Comment by mr-flibble** [comment]
Edit - sorry -  I read it wrong - we use the "custom key" so it does not make sense to deal with it:)

**Comment by JorgenPhi** [comment]
I'm in this situation. On Crashplan 1.4.0 and no adb folder. Is it safe to upgrade it to a newer version?

**Comment by thenickdude** [comment]
@JorgenPhi the new release supports restoring keys from cp.properties files if this file includes a "secureDataKey" line in it, this might cover your situation.
