### ISSUE TITLE
Can't use prefix or specific file to restore

### ISSUE THREAD

**Issue by ricksroad54** [thenickdude/PlanC#22]
I use the latest precompiled version, tried on windows or linux.

If i use prefix or filename with restore option, the restore ending without restore any file and no error showed.
If i use "list" using prefix : no problem, i see file with this prefix

if i try to restore a full backup, after 40min, restore end on error : on AppData Roaming Adobre acorbat tmp file directory.
With this text : Errors were encountered during this restore

Need to restore E path... That is showed when i use list

Thanks

**Comment by thenickdude** [comment]
Can you show the actual commandline you're running, by copy and paste?

**Comment by ricksroad54** [comment]
plan-c.exe --key ... --archive G:\00SAUVEGARDE\712329298483256645 --prefix SOCIAL --dest G:\00SAUVEGARDE\CPH restore



if i precise --prefix, no any restore, but --prefix with list is OK

if i use commande line below 

plan-c.exe --key ... --archive G:\00SAUVEGARDE\712329298483256645 --dest G:\00SAUVEGARDE\CPH restore

Tha restore hang on error after 24Go...

**Comment by thenickdude** [comment]
When you're running "--list" it shows a list of all files that were ever in the backup, including deleted files, but then if you just use "restore" it only restores the newest snapshot from the backup.

When you run "restore", add the "--include-deleted" argument

**Comment by ricksroad54** [comment]
Same, with prefix. estore stop on 'Done !' but no files...

**Comment by ricksroad54** [comment]
i can give you a teamviexer in PM

**Comment by thenickdude** [comment]
Can you share a screenshot of that restore command and the output? Send it to me privately at n.sherlock@gmail.com

**Comment by ricksroad54** [comment]
Screenshot sended, please check your spam too. Thanks

**Comment by ricksroad54** [comment]
Need to specify full path when use restore option.  Thanks Mr. Sherlock
