### ISSUE TITLE
Fatal error opening backup archive: Failed to open file manifest file path\cpfmf

### ISSUE THREAD

**Issue by eternalrevolt** [thenickdude/PlanC#23]
Was able to recover my key from adb, but get this error when trying to list or restore.

**Comment by thenickdude** [comment]
What path are you giving Plan C to point to your backup archive, and what files are in that directory? Is there a cpfmf file?

**Comment by eternalrevolt** [comment]
giving it the full path to the directory (c:\folder\folder\crashplanhomebackup\), and there is a cpfmf file there.

**Comment by thenickdude** [comment]
Can you give the actual literal path you're giving it? Things like spaces and slashes could cause issues.

The backup directory name is usually a very long string of numbers

**Comment by eternalrevolt** [comment]
C:\Users\FamilyName\Desktop\CrashPlanHomeBackup>plan-c --key A92Restofkey --archive C:\Users\FamilyName\Desktop\CrashPlanHomeBackup restore --dry-run
Fatal error opening backup archive: Failed to open file manifest file 'C:\Users\FamilyName\Desktop\CrashPlanHomeBackup\cpfmf'

**Comment by thenickdude** [comment]
Try "--archive .", since you're already inside the target directory.

**Comment by eternalrevolt** [comment]
Well, apparently rubber ducking this with you was enough to figure it out, this command finally worked.

C:\Users\FamilyName\Desktop\CrashPlanHomeBackup>plan-c --key A92restofeky --archive C:\Users\FamilyName\Desktop\CrashPlanHomeBackup\469181561102139758 restore --dry-run

"469181561102139758" actually had the cpfmf file.

I had tried this from another directory, inside the directory, with and without the subdirectory. Also sometimes got bad block error.

Much appreciated.
