### ISSUE TITLE
Code for Custom Key

### ISSUE THREAD

**Issue by MoHf7f4** [thenickdude/PlanC#6]
Could someone post an example of their ADB key?

I'd like to figure out a way to convert the custom keys to fit the format but I don't have any instances of a full account key to work from.

**Comment by einarthoris** [comment]
I have a backup archive and a custom key - so trying to find a solution.

As far as I understand - I need the encryption key in HEX format - but I have a key in ascii format (76 characters).

So we need to figure out how crashplan was converting the custom keys to binary (or HEX).

Hoping someone can figure this out..

**Comment by featherbread** [comment]
The custom key does seem to be the exact key that PlanC needs, the only difference is that the CrashPlan app encodes it as base64 (the "76 character" form you mentioned, @einarthoris) instead of hex.

If you have the base64 encoded key in a file, you should be able to re-encode it like so:

```
base64 --decode $FILE_CONTAINING_KEY | xxd -p -c 256
```

Then just use the output as the `--key` argument to `plan-c`.

**Comment by einarthoris** [comment]
Hi.

I tried doing the base64 decode - the key I have is: "8ppm2s/us+u5bsnW2pePb0TppT8SVu5Olm5ZahX7CsoLrX3P4DRQXoyuFhEk5J7fEUFvYDWrxNU="

The base64 decode gives me: 
"f29a66dacfeeb3ebb96ec9d6da978f6f44e9a53f1256ee4e966e596a15fb0aca0bad7dcfe034505e8cae161124e49edf11416f6035abc4d5"

The result is 112 characters - I think the key is supposed to be around 56 chars - but not sure on that one.

At least if I try to use this key I get the following:

./plan-c --key f29a66dacfeeb3ebb96ec9d6da978f6f44e9a53f1256ee4e966e596a15fb0aca0bad7dcfe034505e8cae161124e49edf11416f6035abc4d5 --archive /media/palli/722098793628274394 list
terminate called after throwing an instance of 'BadPaddingException'
  what():  Bad padding
Aborted (core dumped)

Thank you.
Einar.

**Comment by featherbread** [comment]
Hmm. Unfortunately I'm not sure what the difference is between us. The error is consistent with the key being incorrect, but I don't know why that's the case here.

Older versions of CrashPlan used Blowfish encryption with a 448-bit key. Given that a hexadecimal form can encode 4 bits per character, a 112 character result should make sense. It happened to work for me, but there may be some other detail I'm missing for more general cases.

(Also, as a more general guidance… I would recommend against posting any kind of "secret," like your decryption key, to GitHub in the future. Some kind of placeholder, and perhaps the length of the key, is enough.)

**Comment by MoHf7f4** [comment]
I just did this.  I have 112 character key and it worked.

I'd include this method on the front page.  This was an incredible help.

**Comment by einarthoris** [comment]
Thats great to hear @MoHf7f4 - That confirms that I must have the wrong key - I wasn't 100% sure that I used this one for the computer-computer backups - but I did use it for the cloud backups..
