### ISSUE TITLE
Files not being restored

### ISSUE THREAD

**Issue by jpopham** [thenickdude/PlanC#8]
I'm having difficulty restoring files which are deep down in the directory structure. 
For example restoring a file that was at
 /Users/John 1/Pictures 
worked OK but a files at 
/Users/John 1/Documents/John/John Files/My Documents/PB Docs/John
listed Ok but when attempting to restore I got the messages:
_Caching block indexes in memory...
Restoring files...
Done!_
but no files were restored

**Comment by thenickdude** [comment]
Double check that you are properly quoting paths that contain spaces in your command line.
